name: Build, Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run pytest
        run: pytest tests/ 


  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
